# Generated by Django 4.1 on 2022-09-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuteurPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dominique Megnidro', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=128, verbose_name='légende')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Exemple premier-article prendre en considération le tiret')),
                ('title', models.CharField(max_length=500, verbose_name='titre blog')),
                ('subtitle', models.CharField(max_length=500, verbose_name='sous titre')),
                ('contenu', models.TextField(max_length=800, verbose_name='contenu blog')),
                ('description', models.TextField(max_length=800, verbose_name='contenu blog 2')),
                ('titles', models.CharField(max_length=500, verbose_name='titre 2')),
                ('photo', models.ImageField(upload_to='photo blog')),
                ('contenus', models.TextField(blank=True, max_length=800, verbose_name='paragraph 2')),
                ('descriptions', models.TextField(blank=True, max_length=800, verbose_name='paragraph contenu 2')),
                ('datepub', models.DateField(auto_now_add=True, verbose_name='Date de publication')),
                ('published', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.categorieblogs')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.photo')),
            ],
        ),
    ]
