# Generated by Django 4.1 on 2022-09-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-datepub'], 'verbose_name': 'Blog'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='auteur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.auteurpost'),
            preserve_default=False,
        ),
    ]
